services:
  api:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile

    env_file: [.env]
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    depends_on: [mysql]
    restart: on-failure

  mysql:
    platform: linux/arm64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: